// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XLENET_H
#define XLENET_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xlenet_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilite_BaseAddress;
} XLenet_Config;
#endif

typedef struct {
    u32 Axilite_BaseAddress;
    u32 IsReady;
} XLenet;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XLenet_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XLenet_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XLenet_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XLenet_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XLenet_Initialize(XLenet *InstancePtr, u16 DeviceId);
XLenet_Config* XLenet_LookupConfig(u16 DeviceId);
int XLenet_CfgInitialize(XLenet *InstancePtr, XLenet_Config *ConfigPtr);
#else
int XLenet_Initialize(XLenet *InstancePtr, const char* InstanceName);
int XLenet_Release(XLenet *InstancePtr);
#endif

void XLenet_Start(XLenet *InstancePtr);
u32 XLenet_IsDone(XLenet *InstancePtr);
u32 XLenet_IsIdle(XLenet *InstancePtr);
u32 XLenet_IsReady(XLenet *InstancePtr);
void XLenet_EnableAutoRestart(XLenet *InstancePtr);
void XLenet_DisableAutoRestart(XLenet *InstancePtr);

void XLenet_Set_data_in_size_x(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_data_in_size_x(XLenet *InstancePtr);
void XLenet_Set_data_in_size_y(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_data_in_size_y(XLenet *InstancePtr);
void XLenet_Set_data_in_size_z(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_data_in_size_z(XLenet *InstancePtr);
void XLenet_Set_conv_size_x(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_conv_size_x(XLenet *InstancePtr);
void XLenet_Set_conv_size_y(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_conv_size_y(XLenet *InstancePtr);
void XLenet_Set_conv_size_z(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_conv_size_z(XLenet *InstancePtr);
void XLenet_Set_relu_size_x(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_relu_size_x(XLenet *InstancePtr);
void XLenet_Set_relu_size_y(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_relu_size_y(XLenet *InstancePtr);
void XLenet_Set_relu_size_z(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_relu_size_z(XLenet *InstancePtr);
void XLenet_Set_pool_size_x(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_pool_size_x(XLenet *InstancePtr);
void XLenet_Set_pool_size_y(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_pool_size_y(XLenet *InstancePtr);
void XLenet_Set_pool_size_z(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_pool_size_z(XLenet *InstancePtr);
void XLenet_Set_fc_size_x(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_fc_size_x(XLenet *InstancePtr);
void XLenet_Set_fc_size_y(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_fc_size_y(XLenet *InstancePtr);
void XLenet_Set_fc_size_z(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_fc_size_z(XLenet *InstancePtr);
void XLenet_Set_data_out_size_x(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_data_out_size_x(XLenet *InstancePtr);
void XLenet_Set_data_out_size_y(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_data_out_size_y(XLenet *InstancePtr);
void XLenet_Set_data_out_size_z(XLenet *InstancePtr, u32 Data);
u32 XLenet_Get_data_out_size_z(XLenet *InstancePtr);
u32 XLenet_Get_data_in_data_V_BaseAddress(XLenet *InstancePtr);
u32 XLenet_Get_data_in_data_V_HighAddress(XLenet *InstancePtr);
u32 XLenet_Get_data_in_data_V_TotalBytes(XLenet *InstancePtr);
u32 XLenet_Get_data_in_data_V_BitWidth(XLenet *InstancePtr);
u32 XLenet_Get_data_in_data_V_Depth(XLenet *InstancePtr);
u32 XLenet_Write_data_in_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Read_data_in_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Write_data_in_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);
u32 XLenet_Read_data_in_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);
u32 XLenet_Get_conv_data_V_BaseAddress(XLenet *InstancePtr);
u32 XLenet_Get_conv_data_V_HighAddress(XLenet *InstancePtr);
u32 XLenet_Get_conv_data_V_TotalBytes(XLenet *InstancePtr);
u32 XLenet_Get_conv_data_V_BitWidth(XLenet *InstancePtr);
u32 XLenet_Get_conv_data_V_Depth(XLenet *InstancePtr);
u32 XLenet_Write_conv_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Read_conv_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Write_conv_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);
u32 XLenet_Read_conv_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);
u32 XLenet_Get_relu_data_V_BaseAddress(XLenet *InstancePtr);
u32 XLenet_Get_relu_data_V_HighAddress(XLenet *InstancePtr);
u32 XLenet_Get_relu_data_V_TotalBytes(XLenet *InstancePtr);
u32 XLenet_Get_relu_data_V_BitWidth(XLenet *InstancePtr);
u32 XLenet_Get_relu_data_V_Depth(XLenet *InstancePtr);
u32 XLenet_Write_relu_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Read_relu_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Write_relu_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);
u32 XLenet_Read_relu_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);
u32 XLenet_Get_pool_data_V_BaseAddress(XLenet *InstancePtr);
u32 XLenet_Get_pool_data_V_HighAddress(XLenet *InstancePtr);
u32 XLenet_Get_pool_data_V_TotalBytes(XLenet *InstancePtr);
u32 XLenet_Get_pool_data_V_BitWidth(XLenet *InstancePtr);
u32 XLenet_Get_pool_data_V_Depth(XLenet *InstancePtr);
u32 XLenet_Write_pool_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Read_pool_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Write_pool_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);
u32 XLenet_Read_pool_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);
u32 XLenet_Get_fc_data_V_BaseAddress(XLenet *InstancePtr);
u32 XLenet_Get_fc_data_V_HighAddress(XLenet *InstancePtr);
u32 XLenet_Get_fc_data_V_TotalBytes(XLenet *InstancePtr);
u32 XLenet_Get_fc_data_V_BitWidth(XLenet *InstancePtr);
u32 XLenet_Get_fc_data_V_Depth(XLenet *InstancePtr);
u32 XLenet_Write_fc_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Read_fc_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Write_fc_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);
u32 XLenet_Read_fc_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);
u32 XLenet_Get_data_out_data_V_BaseAddress(XLenet *InstancePtr);
u32 XLenet_Get_data_out_data_V_HighAddress(XLenet *InstancePtr);
u32 XLenet_Get_data_out_data_V_TotalBytes(XLenet *InstancePtr);
u32 XLenet_Get_data_out_data_V_BitWidth(XLenet *InstancePtr);
u32 XLenet_Get_data_out_data_V_Depth(XLenet *InstancePtr);
u32 XLenet_Write_data_out_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Read_data_out_data_V_Words(XLenet *InstancePtr, int offset, int *data, int length);
u32 XLenet_Write_data_out_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);
u32 XLenet_Read_data_out_data_V_Bytes(XLenet *InstancePtr, int offset, char *data, int length);

void XLenet_InterruptGlobalEnable(XLenet *InstancePtr);
void XLenet_InterruptGlobalDisable(XLenet *InstancePtr);
void XLenet_InterruptEnable(XLenet *InstancePtr, u32 Mask);
void XLenet_InterruptDisable(XLenet *InstancePtr, u32 Mask);
void XLenet_InterruptClear(XLenet *InstancePtr, u32 Mask);
u32 XLenet_InterruptGetEnabled(XLenet *InstancePtr);
u32 XLenet_InterruptGetStatus(XLenet *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
