-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use IEEE.NUMERIC_STD.all;

entity Lenet_axilite_s_axi is
generic (
    C_S_AXI_ADDR_WIDTH    : INTEGER := 9;
    C_S_AXI_DATA_WIDTH    : INTEGER := 32);
port (
    -- axi4 lite slave signals
    ACLK                  :in   STD_LOGIC;
    ARESET                :in   STD_LOGIC;
    ACLK_EN               :in   STD_LOGIC;
    AWADDR                :in   STD_LOGIC_VECTOR(C_S_AXI_ADDR_WIDTH-1 downto 0);
    AWVALID               :in   STD_LOGIC;
    AWREADY               :out  STD_LOGIC;
    WDATA                 :in   STD_LOGIC_VECTOR(C_S_AXI_DATA_WIDTH-1 downto 0);
    WSTRB                 :in   STD_LOGIC_VECTOR(C_S_AXI_DATA_WIDTH/8-1 downto 0);
    WVALID                :in   STD_LOGIC;
    WREADY                :out  STD_LOGIC;
    BRESP                 :out  STD_LOGIC_VECTOR(1 downto 0);
    BVALID                :out  STD_LOGIC;
    BREADY                :in   STD_LOGIC;
    ARADDR                :in   STD_LOGIC_VECTOR(C_S_AXI_ADDR_WIDTH-1 downto 0);
    ARVALID               :in   STD_LOGIC;
    ARREADY               :out  STD_LOGIC;
    RDATA                 :out  STD_LOGIC_VECTOR(C_S_AXI_DATA_WIDTH-1 downto 0);
    RRESP                 :out  STD_LOGIC_VECTOR(1 downto 0);
    RVALID                :out  STD_LOGIC;
    RREADY                :in   STD_LOGIC;
    interrupt             :out  STD_LOGIC;
    -- user signals
    ap_start              :out  STD_LOGIC;
    ap_done               :in   STD_LOGIC;
    ap_ready              :in   STD_LOGIC;
    ap_idle               :in   STD_LOGIC;
    data_in_data_V_address0 :in   STD_LOGIC_VECTOR(2 downto 0);
    data_in_data_V_ce0    :in   STD_LOGIC;
    data_in_data_V_q0     :out  STD_LOGIC_VECTOR(15 downto 0);
    data_in_size_x        :out  STD_LOGIC_VECTOR(31 downto 0);
    data_in_size_y        :out  STD_LOGIC_VECTOR(31 downto 0);
    data_in_size_z        :out  STD_LOGIC_VECTOR(31 downto 0);
    conv_data_V_address0  :in   STD_LOGIC_VECTOR(2 downto 0);
    conv_data_V_ce0       :in   STD_LOGIC;
    conv_data_V_we0       :in   STD_LOGIC;
    conv_data_V_d0        :in   STD_LOGIC_VECTOR(15 downto 0);
    conv_size_x           :out  STD_LOGIC_VECTOR(31 downto 0);
    conv_size_y           :out  STD_LOGIC_VECTOR(31 downto 0);
    conv_size_z           :out  STD_LOGIC_VECTOR(31 downto 0);
    relu_data_V_address0  :in   STD_LOGIC_VECTOR(2 downto 0);
    relu_data_V_ce0       :in   STD_LOGIC;
    relu_data_V_we0       :in   STD_LOGIC;
    relu_data_V_d0        :in   STD_LOGIC_VECTOR(15 downto 0);
    relu_size_x           :out  STD_LOGIC_VECTOR(31 downto 0);
    relu_size_y           :out  STD_LOGIC_VECTOR(31 downto 0);
    relu_size_z           :out  STD_LOGIC_VECTOR(31 downto 0);
    pool_data_V_address0  :in   STD_LOGIC_VECTOR(2 downto 0);
    pool_data_V_ce0       :in   STD_LOGIC;
    pool_data_V_we0       :in   STD_LOGIC;
    pool_data_V_d0        :in   STD_LOGIC_VECTOR(15 downto 0);
    pool_size_x           :out  STD_LOGIC_VECTOR(31 downto 0);
    pool_size_y           :out  STD_LOGIC_VECTOR(31 downto 0);
    pool_size_z           :out  STD_LOGIC_VECTOR(31 downto 0);
    fc_data_V_address0    :in   STD_LOGIC_VECTOR(2 downto 0);
    fc_data_V_ce0         :in   STD_LOGIC;
    fc_data_V_we0         :in   STD_LOGIC;
    fc_data_V_d0          :in   STD_LOGIC_VECTOR(15 downto 0);
    fc_size_x             :out  STD_LOGIC_VECTOR(31 downto 0);
    fc_size_y             :out  STD_LOGIC_VECTOR(31 downto 0);
    fc_size_z             :out  STD_LOGIC_VECTOR(31 downto 0);
    data_out_data_V_address0 :in   STD_LOGIC_VECTOR(4 downto 0);
    data_out_data_V_ce0   :in   STD_LOGIC;
    data_out_data_V_we0   :in   STD_LOGIC;
    data_out_data_V_d0    :in   STD_LOGIC_VECTOR(15 downto 0);
    data_out_size_x       :out  STD_LOGIC_VECTOR(31 downto 0);
    data_out_size_y       :out  STD_LOGIC_VECTOR(31 downto 0);
    data_out_size_z       :out  STD_LOGIC_VECTOR(31 downto 0)
);
end entity Lenet_axilite_s_axi;

-- ------------------------Address Info-------------------
-- 0x000 : Control signals
--         bit 0  - ap_start (Read/Write/COH)
--         bit 1  - ap_done (Read/COR)
--         bit 2  - ap_idle (Read)
--         bit 3  - ap_ready (Read)
--         bit 7  - auto_restart (Read/Write)
--         others - reserved
-- 0x004 : Global Interrupt Enable Register
--         bit 0  - Global Interrupt Enable (Read/Write)
--         others - reserved
-- 0x008 : IP Interrupt Enable Register (Read/Write)
--         bit 0  - Channel 0 (ap_done)
--         bit 1  - Channel 1 (ap_ready)
--         others - reserved
-- 0x00c : IP Interrupt Status Register (Read/TOW)
--         bit 0  - Channel 0 (ap_done)
--         bit 1  - Channel 1 (ap_ready)
--         others - reserved
-- 0x020 : Data signal of data_in_size_x
--         bit 31~0 - data_in_size_x[31:0] (Read/Write)
-- 0x024 : reserved
-- 0x028 : Data signal of data_in_size_y
--         bit 31~0 - data_in_size_y[31:0] (Read/Write)
-- 0x02c : reserved
-- 0x030 : Data signal of data_in_size_z
--         bit 31~0 - data_in_size_z[31:0] (Read/Write)
-- 0x034 : reserved
-- 0x050 : Data signal of conv_size_x
--         bit 31~0 - conv_size_x[31:0] (Read/Write)
-- 0x054 : reserved
-- 0x058 : Data signal of conv_size_y
--         bit 31~0 - conv_size_y[31:0] (Read/Write)
-- 0x05c : reserved
-- 0x060 : Data signal of conv_size_z
--         bit 31~0 - conv_size_z[31:0] (Read/Write)
-- 0x064 : reserved
-- 0x080 : Data signal of relu_size_x
--         bit 31~0 - relu_size_x[31:0] (Read/Write)
-- 0x084 : reserved
-- 0x088 : Data signal of relu_size_y
--         bit 31~0 - relu_size_y[31:0] (Read/Write)
-- 0x08c : reserved
-- 0x090 : Data signal of relu_size_z
--         bit 31~0 - relu_size_z[31:0] (Read/Write)
-- 0x094 : reserved
-- 0x0b0 : Data signal of pool_size_x
--         bit 31~0 - pool_size_x[31:0] (Read/Write)
-- 0x0b4 : reserved
-- 0x0b8 : Data signal of pool_size_y
--         bit 31~0 - pool_size_y[31:0] (Read/Write)
-- 0x0bc : reserved
-- 0x0c0 : Data signal of pool_size_z
--         bit 31~0 - pool_size_z[31:0] (Read/Write)
-- 0x0c4 : reserved
-- 0x0e0 : Data signal of fc_size_x
--         bit 31~0 - fc_size_x[31:0] (Read/Write)
-- 0x0e4 : reserved
-- 0x0e8 : Data signal of fc_size_y
--         bit 31~0 - fc_size_y[31:0] (Read/Write)
-- 0x0ec : reserved
-- 0x0f0 : Data signal of fc_size_z
--         bit 31~0 - fc_size_z[31:0] (Read/Write)
-- 0x0f4 : reserved
-- 0x140 : Data signal of data_out_size_x
--         bit 31~0 - data_out_size_x[31:0] (Read/Write)
-- 0x144 : reserved
-- 0x148 : Data signal of data_out_size_y
--         bit 31~0 - data_out_size_y[31:0] (Read/Write)
-- 0x14c : reserved
-- 0x150 : Data signal of data_out_size_z
--         bit 31~0 - data_out_size_z[31:0] (Read/Write)
-- 0x154 : reserved
-- 0x010 ~
-- 0x01f : Memory 'data_in_data_V' (8 * 16b)
--         Word n : bit [15: 0] - data_in_data_V[2n]
--                  bit [31:16] - data_in_data_V[2n+1]
-- 0x040 ~
-- 0x04f : Memory 'conv_data_V' (8 * 16b)
--         Word n : bit [15: 0] - conv_data_V[2n]
--                  bit [31:16] - conv_data_V[2n+1]
-- 0x070 ~
-- 0x07f : Memory 'relu_data_V' (8 * 16b)
--         Word n : bit [15: 0] - relu_data_V[2n]
--                  bit [31:16] - relu_data_V[2n+1]
-- 0x0a0 ~
-- 0x0af : Memory 'pool_data_V' (8 * 16b)
--         Word n : bit [15: 0] - pool_data_V[2n]
--                  bit [31:16] - pool_data_V[2n+1]
-- 0x0d0 ~
-- 0x0df : Memory 'fc_data_V' (8 * 16b)
--         Word n : bit [15: 0] - fc_data_V[2n]
--                  bit [31:16] - fc_data_V[2n+1]
-- 0x100 ~
-- 0x13f : Memory 'data_out_data_V' (27 * 16b)
--         Word n : bit [15: 0] - data_out_data_V[2n]
--                  bit [31:16] - data_out_data_V[2n+1]
-- (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

architecture behave of Lenet_axilite_s_axi is
    type states is (wridle, wrdata, wrresp, wrreset, rdidle, rddata, rdreset);  -- read and write fsm states
    signal wstate  : states := wrreset;
    signal rstate  : states := rdreset;
    signal wnext, rnext: states;
    constant ADDR_AP_CTRL                : INTEGER := 16#000#;
    constant ADDR_GIE                    : INTEGER := 16#004#;
    constant ADDR_IER                    : INTEGER := 16#008#;
    constant ADDR_ISR                    : INTEGER := 16#00c#;
    constant ADDR_DATA_IN_SIZE_X_DATA_0  : INTEGER := 16#020#;
    constant ADDR_DATA_IN_SIZE_X_CTRL    : INTEGER := 16#024#;
    constant ADDR_DATA_IN_SIZE_Y_DATA_0  : INTEGER := 16#028#;
    constant ADDR_DATA_IN_SIZE_Y_CTRL    : INTEGER := 16#02c#;
    constant ADDR_DATA_IN_SIZE_Z_DATA_0  : INTEGER := 16#030#;
    constant ADDR_DATA_IN_SIZE_Z_CTRL    : INTEGER := 16#034#;
    constant ADDR_CONV_SIZE_X_DATA_0     : INTEGER := 16#050#;
    constant ADDR_CONV_SIZE_X_CTRL       : INTEGER := 16#054#;
    constant ADDR_CONV_SIZE_Y_DATA_0     : INTEGER := 16#058#;
    constant ADDR_CONV_SIZE_Y_CTRL       : INTEGER := 16#05c#;
    constant ADDR_CONV_SIZE_Z_DATA_0     : INTEGER := 16#060#;
    constant ADDR_CONV_SIZE_Z_CTRL       : INTEGER := 16#064#;
    constant ADDR_RELU_SIZE_X_DATA_0     : INTEGER := 16#080#;
    constant ADDR_RELU_SIZE_X_CTRL       : INTEGER := 16#084#;
    constant ADDR_RELU_SIZE_Y_DATA_0     : INTEGER := 16#088#;
    constant ADDR_RELU_SIZE_Y_CTRL       : INTEGER := 16#08c#;
    constant ADDR_RELU_SIZE_Z_DATA_0     : INTEGER := 16#090#;
    constant ADDR_RELU_SIZE_Z_CTRL       : INTEGER := 16#094#;
    constant ADDR_POOL_SIZE_X_DATA_0     : INTEGER := 16#0b0#;
    constant ADDR_POOL_SIZE_X_CTRL       : INTEGER := 16#0b4#;
    constant ADDR_POOL_SIZE_Y_DATA_0     : INTEGER := 16#0b8#;
    constant ADDR_POOL_SIZE_Y_CTRL       : INTEGER := 16#0bc#;
    constant ADDR_POOL_SIZE_Z_DATA_0     : INTEGER := 16#0c0#;
    constant ADDR_POOL_SIZE_Z_CTRL       : INTEGER := 16#0c4#;
    constant ADDR_FC_SIZE_X_DATA_0       : INTEGER := 16#0e0#;
    constant ADDR_FC_SIZE_X_CTRL         : INTEGER := 16#0e4#;
    constant ADDR_FC_SIZE_Y_DATA_0       : INTEGER := 16#0e8#;
    constant ADDR_FC_SIZE_Y_CTRL         : INTEGER := 16#0ec#;
    constant ADDR_FC_SIZE_Z_DATA_0       : INTEGER := 16#0f0#;
    constant ADDR_FC_SIZE_Z_CTRL         : INTEGER := 16#0f4#;
    constant ADDR_DATA_OUT_SIZE_X_DATA_0 : INTEGER := 16#140#;
    constant ADDR_DATA_OUT_SIZE_X_CTRL   : INTEGER := 16#144#;
    constant ADDR_DATA_OUT_SIZE_Y_DATA_0 : INTEGER := 16#148#;
    constant ADDR_DATA_OUT_SIZE_Y_CTRL   : INTEGER := 16#14c#;
    constant ADDR_DATA_OUT_SIZE_Z_DATA_0 : INTEGER := 16#150#;
    constant ADDR_DATA_OUT_SIZE_Z_CTRL   : INTEGER := 16#154#;
    constant ADDR_DATA_IN_DATA_V_BASE    : INTEGER := 16#010#;
    constant ADDR_DATA_IN_DATA_V_HIGH    : INTEGER := 16#01f#;
    constant ADDR_CONV_DATA_V_BASE       : INTEGER := 16#040#;
    constant ADDR_CONV_DATA_V_HIGH       : INTEGER := 16#04f#;
    constant ADDR_RELU_DATA_V_BASE       : INTEGER := 16#070#;
    constant ADDR_RELU_DATA_V_HIGH       : INTEGER := 16#07f#;
    constant ADDR_POOL_DATA_V_BASE       : INTEGER := 16#0a0#;
    constant ADDR_POOL_DATA_V_HIGH       : INTEGER := 16#0af#;
    constant ADDR_FC_DATA_V_BASE         : INTEGER := 16#0d0#;
    constant ADDR_FC_DATA_V_HIGH         : INTEGER := 16#0df#;
    constant ADDR_DATA_OUT_DATA_V_BASE   : INTEGER := 16#100#;
    constant ADDR_DATA_OUT_DATA_V_HIGH   : INTEGER := 16#13f#;
    constant ADDR_BITS         : INTEGER := 9;

    signal waddr               : UNSIGNED(ADDR_BITS-1 downto 0);
    signal wmask               : UNSIGNED(31 downto 0);
    signal aw_hs               : STD_LOGIC;
    signal w_hs                : STD_LOGIC;
    signal rdata_data          : UNSIGNED(31 downto 0);
    signal ar_hs               : STD_LOGIC;
    signal raddr               : UNSIGNED(ADDR_BITS-1 downto 0);
    signal AWREADY_t           : STD_LOGIC;
    signal WREADY_t            : STD_LOGIC;
    signal ARREADY_t           : STD_LOGIC;
    signal RVALID_t            : STD_LOGIC;
    -- internal registers
    signal int_ap_idle         : STD_LOGIC;
    signal int_ap_ready        : STD_LOGIC;
    signal int_ap_done         : STD_LOGIC := '0';
    signal int_ap_start        : STD_LOGIC := '0';
    signal int_auto_restart    : STD_LOGIC := '0';
    signal int_gie             : STD_LOGIC := '0';
    signal int_ier             : UNSIGNED(1 downto 0) := (others => '0');
    signal int_isr             : UNSIGNED(1 downto 0) := (others => '0');
    signal int_data_in_size_x  : UNSIGNED(31 downto 0) := (others => '0');
    signal int_data_in_size_y  : UNSIGNED(31 downto 0) := (others => '0');
    signal int_data_in_size_z  : UNSIGNED(31 downto 0) := (others => '0');
    signal int_conv_size_x     : UNSIGNED(31 downto 0) := (others => '0');
    signal int_conv_size_y     : UNSIGNED(31 downto 0) := (others => '0');
    signal int_conv_size_z     : UNSIGNED(31 downto 0) := (others => '0');
    signal int_relu_size_x     : UNSIGNED(31 downto 0) := (others => '0');
    signal int_relu_size_y     : UNSIGNED(31 downto 0) := (others => '0');
    signal int_relu_size_z     : UNSIGNED(31 downto 0) := (others => '0');
    signal int_pool_size_x     : UNSIGNED(31 downto 0) := (others => '0');
    signal int_pool_size_y     : UNSIGNED(31 downto 0) := (others => '0');
    signal int_pool_size_z     : UNSIGNED(31 downto 0) := (others => '0');
    signal int_fc_size_x       : UNSIGNED(31 downto 0) := (others => '0');
    signal int_fc_size_y       : UNSIGNED(31 downto 0) := (others => '0');
    signal int_fc_size_z       : UNSIGNED(31 downto 0) := (others => '0');
    signal int_data_out_size_x : UNSIGNED(31 downto 0) := (others => '0');
    signal int_data_out_size_y : UNSIGNED(31 downto 0) := (others => '0');
    signal int_data_out_size_z : UNSIGNED(31 downto 0) := (others => '0');
    -- memory signals
    signal int_data_in_data_V_address0 : UNSIGNED(1 downto 0);
    signal int_data_in_data_V_ce0 : STD_LOGIC;
    signal int_data_in_data_V_we0 : STD_LOGIC;
    signal int_data_in_data_V_be0 : UNSIGNED(3 downto 0);
    signal int_data_in_data_V_d0 : UNSIGNED(31 downto 0);
    signal int_data_in_data_V_q0 : UNSIGNED(31 downto 0);
    signal int_data_in_data_V_address1 : UNSIGNED(1 downto 0);
    signal int_data_in_data_V_ce1 : STD_LOGIC;
    signal int_data_in_data_V_we1 : STD_LOGIC;
    signal int_data_in_data_V_be1 : UNSIGNED(3 downto 0);
    signal int_data_in_data_V_d1 : UNSIGNED(31 downto 0);
    signal int_data_in_data_V_q1 : UNSIGNED(31 downto 0);
    signal int_data_in_data_V_read : STD_LOGIC;
    signal int_data_in_data_V_write : STD_LOGIC;
    signal int_data_in_data_V_shift : UNSIGNED(0 downto 0);
    signal int_conv_data_V_address0 : UNSIGNED(1 downto 0);
    signal int_conv_data_V_ce0 : STD_LOGIC;
    signal int_conv_data_V_we0 : STD_LOGIC;
    signal int_conv_data_V_be0 : UNSIGNED(3 downto 0);
    signal int_conv_data_V_d0  : UNSIGNED(31 downto 0);
    signal int_conv_data_V_q0  : UNSIGNED(31 downto 0);
    signal int_conv_data_V_address1 : UNSIGNED(1 downto 0);
    signal int_conv_data_V_ce1 : STD_LOGIC;
    signal int_conv_data_V_we1 : STD_LOGIC;
    signal int_conv_data_V_be1 : UNSIGNED(3 downto 0);
    signal int_conv_data_V_d1  : UNSIGNED(31 downto 0);
    signal int_conv_data_V_q1  : UNSIGNED(31 downto 0);
    signal int_conv_data_V_read : STD_LOGIC;
    signal int_conv_data_V_write : STD_LOGIC;
    signal int_conv_data_V_shift : UNSIGNED(0 downto 0);
    signal int_relu_data_V_address0 : UNSIGNED(1 downto 0);
    signal int_relu_data_V_ce0 : STD_LOGIC;
    signal int_relu_data_V_we0 : STD_LOGIC;
    signal int_relu_data_V_be0 : UNSIGNED(3 downto 0);
    signal int_relu_data_V_d0  : UNSIGNED(31 downto 0);
    signal int_relu_data_V_q0  : UNSIGNED(31 downto 0);
    signal int_relu_data_V_address1 : UNSIGNED(1 downto 0);
    signal int_relu_data_V_ce1 : STD_LOGIC;
    signal int_relu_data_V_we1 : STD_LOGIC;
    signal int_relu_data_V_be1 : UNSIGNED(3 downto 0);
    signal int_relu_data_V_d1  : UNSIGNED(31 downto 0);
    signal int_relu_data_V_q1  : UNSIGNED(31 downto 0);
    signal int_relu_data_V_read : STD_LOGIC;
    signal int_relu_data_V_write : STD_LOGIC;
    signal int_relu_data_V_shift : UNSIGNED(0 downto 0);
    signal int_pool_data_V_address0 : UNSIGNED(1 downto 0);
    signal int_pool_data_V_ce0 : STD_LOGIC;
    signal int_pool_data_V_we0 : STD_LOGIC;
    signal int_pool_data_V_be0 : UNSIGNED(3 downto 0);
    signal int_pool_data_V_d0  : UNSIGNED(31 downto 0);
    signal int_pool_data_V_q0  : UNSIGNED(31 downto 0);
    signal int_pool_data_V_address1 : UNSIGNED(1 downto 0);
    signal int_pool_data_V_ce1 : STD_LOGIC;
    signal int_pool_data_V_we1 : STD_LOGIC;
    signal int_pool_data_V_be1 : UNSIGNED(3 downto 0);
    signal int_pool_data_V_d1  : UNSIGNED(31 downto 0);
    signal int_pool_data_V_q1  : UNSIGNED(31 downto 0);
    signal int_pool_data_V_read : STD_LOGIC;
    signal int_pool_data_V_write : STD_LOGIC;
    signal int_pool_data_V_shift : UNSIGNED(0 downto 0);
    signal int_fc_data_V_address0 : UNSIGNED(1 downto 0);
    signal int_fc_data_V_ce0   : STD_LOGIC;
    signal int_fc_data_V_we0   : STD_LOGIC;
    signal int_fc_data_V_be0   : UNSIGNED(3 downto 0);
    signal int_fc_data_V_d0    : UNSIGNED(31 downto 0);
    signal int_fc_data_V_q0    : UNSIGNED(31 downto 0);
    signal int_fc_data_V_address1 : UNSIGNED(1 downto 0);
    signal int_fc_data_V_ce1   : STD_LOGIC;
    signal int_fc_data_V_we1   : STD_LOGIC;
    signal int_fc_data_V_be1   : UNSIGNED(3 downto 0);
    signal int_fc_data_V_d1    : UNSIGNED(31 downto 0);
    signal int_fc_data_V_q1    : UNSIGNED(31 downto 0);
    signal int_fc_data_V_read  : STD_LOGIC;
    signal int_fc_data_V_write : STD_LOGIC;
    signal int_fc_data_V_shift : UNSIGNED(0 downto 0);
    signal int_data_out_data_V_address0 : UNSIGNED(3 downto 0);
    signal int_data_out_data_V_ce0 : STD_LOGIC;
    signal int_data_out_data_V_we0 : STD_LOGIC;
    signal int_data_out_data_V_be0 : UNSIGNED(3 downto 0);
    signal int_data_out_data_V_d0 : UNSIGNED(31 downto 0);
    signal int_data_out_data_V_q0 : UNSIGNED(31 downto 0);
    signal int_data_out_data_V_address1 : UNSIGNED(3 downto 0);
    signal int_data_out_data_V_ce1 : STD_LOGIC;
    signal int_data_out_data_V_we1 : STD_LOGIC;
    signal int_data_out_data_V_be1 : UNSIGNED(3 downto 0);
    signal int_data_out_data_V_d1 : UNSIGNED(31 downto 0);
    signal int_data_out_data_V_q1 : UNSIGNED(31 downto 0);
    signal int_data_out_data_V_read : STD_LOGIC;
    signal int_data_out_data_V_write : STD_LOGIC;
    signal int_data_out_data_V_shift : UNSIGNED(0 downto 0);

    component Lenet_axilite_s_axi_ram is
        generic (
            BYTES   : INTEGER :=4;
            DEPTH   : INTEGER :=256;
            AWIDTH  : INTEGER :=8);
        port (
            clk0    : in  STD_LOGIC;
            address0: in  UNSIGNED(AWIDTH-1 downto 0);
            ce0     : in  STD_LOGIC;
            we0     : in  STD_LOGIC;
            be0     : in  UNSIGNED(BYTES-1 downto 0);
            d0      : in  UNSIGNED(BYTES*8-1 downto 0);
            q0      : out UNSIGNED(BYTES*8-1 downto 0);
            clk1    : in  STD_LOGIC;
            address1: in  UNSIGNED(AWIDTH-1 downto 0);
            ce1     : in  STD_LOGIC;
            we1     : in  STD_LOGIC;
            be1     : in  UNSIGNED(BYTES-1 downto 0);
            d1      : in  UNSIGNED(BYTES*8-1 downto 0);
            q1      : out UNSIGNED(BYTES*8-1 downto 0));
    end component Lenet_axilite_s_axi_ram;

    function log2 (x : INTEGER) return INTEGER is
        variable n, m : INTEGER;
    begin
        n := 1;
        m := 2;
        while m < x loop
            n := n + 1;
            m := m * 2;
        end loop;
        return n;
    end function log2;

begin
-- ----------------------- Instantiation------------------
-- int_data_in_data_V
int_data_in_data_V : Lenet_axilite_s_axi_ram
generic map (
     BYTES    => 4,
     DEPTH    => 4,
     AWIDTH   => log2(4))
port map (
     clk0     => ACLK,
     address0 => int_data_in_data_V_address0,
     ce0      => int_data_in_data_V_ce0,
     we0      => int_data_in_data_V_we0,
     be0      => int_data_in_data_V_be0,
     d0       => int_data_in_data_V_d0,
     q0       => int_data_in_data_V_q0,
     clk1     => ACLK,
     address1 => int_data_in_data_V_address1,
     ce1      => int_data_in_data_V_ce1,
     we1      => int_data_in_data_V_we1,
     be1      => int_data_in_data_V_be1,
     d1       => int_data_in_data_V_d1,
     q1       => int_data_in_data_V_q1);
-- int_conv_data_V
int_conv_data_V : Lenet_axilite_s_axi_ram
generic map (
     BYTES    => 4,
     DEPTH    => 4,
     AWIDTH   => log2(4))
port map (
     clk0     => ACLK,
     address0 => int_conv_data_V_address0,
     ce0      => int_conv_data_V_ce0,
     we0      => int_conv_data_V_we0,
     be0      => int_conv_data_V_be0,
     d0       => int_conv_data_V_d0,
     q0       => int_conv_data_V_q0,
     clk1     => ACLK,
     address1 => int_conv_data_V_address1,
     ce1      => int_conv_data_V_ce1,
     we1      => int_conv_data_V_we1,
     be1      => int_conv_data_V_be1,
     d1       => int_conv_data_V_d1,
     q1       => int_conv_data_V_q1);
-- int_relu_data_V
int_relu_data_V : Lenet_axilite_s_axi_ram
generic map (
     BYTES    => 4,
     DEPTH    => 4,
     AWIDTH   => log2(4))
port map (
     clk0     => ACLK,
     address0 => int_relu_data_V_address0,
     ce0      => int_relu_data_V_ce0,
     we0      => int_relu_data_V_we0,
     be0      => int_relu_data_V_be0,
     d0       => int_relu_data_V_d0,
     q0       => int_relu_data_V_q0,
     clk1     => ACLK,
     address1 => int_relu_data_V_address1,
     ce1      => int_relu_data_V_ce1,
     we1      => int_relu_data_V_we1,
     be1      => int_relu_data_V_be1,
     d1       => int_relu_data_V_d1,
     q1       => int_relu_data_V_q1);
-- int_pool_data_V
int_pool_data_V : Lenet_axilite_s_axi_ram
generic map (
     BYTES    => 4,
     DEPTH    => 4,
     AWIDTH   => log2(4))
port map (
     clk0     => ACLK,
     address0 => int_pool_data_V_address0,
     ce0      => int_pool_data_V_ce0,
     we0      => int_pool_data_V_we0,
     be0      => int_pool_data_V_be0,
     d0       => int_pool_data_V_d0,
     q0       => int_pool_data_V_q0,
     clk1     => ACLK,
     address1 => int_pool_data_V_address1,
     ce1      => int_pool_data_V_ce1,
     we1      => int_pool_data_V_we1,
     be1      => int_pool_data_V_be1,
     d1       => int_pool_data_V_d1,
     q1       => int_pool_data_V_q1);
-- int_fc_data_V
int_fc_data_V : Lenet_axilite_s_axi_ram
generic map (
     BYTES    => 4,
     DEPTH    => 4,
     AWIDTH   => log2(4))
port map (
     clk0     => ACLK,
     address0 => int_fc_data_V_address0,
     ce0      => int_fc_data_V_ce0,
     we0      => int_fc_data_V_we0,
     be0      => int_fc_data_V_be0,
     d0       => int_fc_data_V_d0,
     q0       => int_fc_data_V_q0,
     clk1     => ACLK,
     address1 => int_fc_data_V_address1,
     ce1      => int_fc_data_V_ce1,
     we1      => int_fc_data_V_we1,
     be1      => int_fc_data_V_be1,
     d1       => int_fc_data_V_d1,
     q1       => int_fc_data_V_q1);
-- int_data_out_data_V
int_data_out_data_V : Lenet_axilite_s_axi_ram
generic map (
     BYTES    => 4,
     DEPTH    => 14,
     AWIDTH   => log2(14))
port map (
     clk0     => ACLK,
     address0 => int_data_out_data_V_address0,
     ce0      => int_data_out_data_V_ce0,
     we0      => int_data_out_data_V_we0,
     be0      => int_data_out_data_V_be0,
     d0       => int_data_out_data_V_d0,
     q0       => int_data_out_data_V_q0,
     clk1     => ACLK,
     address1 => int_data_out_data_V_address1,
     ce1      => int_data_out_data_V_ce1,
     we1      => int_data_out_data_V_we1,
     be1      => int_data_out_data_V_be1,
     d1       => int_data_out_data_V_d1,
     q1       => int_data_out_data_V_q1);

-- ----------------------- AXI WRITE ---------------------
    AWREADY_t <=  '1' when wstate = wridle else '0';
    AWREADY   <=  AWREADY_t;
    WREADY_t  <=  '1' when wstate = wrdata else '0';
    WREADY    <=  WREADY_t;
    BRESP     <=  "00";  -- OKAY
    BVALID    <=  '1' when wstate = wrresp else '0';
    wmask     <=  (31 downto 24 => WSTRB(3), 23 downto 16 => WSTRB(2), 15 downto 8 => WSTRB(1), 7 downto 0 => WSTRB(0));
    aw_hs     <=  AWVALID and AWREADY_t;
    w_hs      <=  WVALID and WREADY_t;

    -- write FSM
    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                wstate <= wrreset;
            elsif (ACLK_EN = '1') then
                wstate <= wnext;
            end if;
        end if;
    end process;

    process (wstate, AWVALID, WVALID, BREADY)
    begin
        case (wstate) is
        when wridle =>
            if (AWVALID = '1') then
                wnext <= wrdata;
            else
                wnext <= wridle;
            end if;
        when wrdata =>
            if (WVALID = '1') then
                wnext <= wrresp;
            else
                wnext <= wrdata;
            end if;
        when wrresp =>
            if (BREADY = '1') then
                wnext <= wridle;
            else
                wnext <= wrresp;
            end if;
        when others =>
            wnext <= wridle;
        end case;
    end process;

    waddr_proc : process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (aw_hs = '1') then
                    waddr <= UNSIGNED(AWADDR(ADDR_BITS-1 downto 0));
                end if;
            end if;
        end if;
    end process;

-- ----------------------- AXI READ ----------------------
    ARREADY_t <= '1' when (rstate = rdidle) else '0';
    ARREADY <= ARREADY_t;
    RDATA   <= STD_LOGIC_VECTOR(rdata_data);
    RRESP   <= "00";  -- OKAY
    RVALID_t  <= '1' when (rstate = rddata) and (int_data_in_data_V_read = '0') and (int_conv_data_V_read = '0') and (int_relu_data_V_read = '0') and (int_pool_data_V_read = '0') and (int_fc_data_V_read = '0') and (int_data_out_data_V_read = '0') else '0';
    RVALID    <= RVALID_t;
    ar_hs   <= ARVALID and ARREADY_t;
    raddr   <= UNSIGNED(ARADDR(ADDR_BITS-1 downto 0));

    -- read FSM
    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                rstate <= rdreset;
            elsif (ACLK_EN = '1') then
                rstate <= rnext;
            end if;
        end if;
    end process;

    process (rstate, ARVALID, RREADY, RVALID_t)
    begin
        case (rstate) is
        when rdidle =>
            if (ARVALID = '1') then
                rnext <= rddata;
            else
                rnext <= rdidle;
            end if;
        when rddata =>
            if (RREADY = '1' and RVALID_t = '1') then
                rnext <= rdidle;
            else
                rnext <= rddata;
            end if;
        when others =>
            rnext <= rdidle;
        end case;
    end process;

    rdata_proc : process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (ar_hs = '1') then
                    case (TO_INTEGER(raddr)) is
                    when ADDR_AP_CTRL =>
                        rdata_data <= (7 => int_auto_restart, 3 => int_ap_ready, 2 => int_ap_idle, 1 => int_ap_done, 0 => int_ap_start, others => '0');
                    when ADDR_GIE =>
                        rdata_data <= (0 => int_gie, others => '0');
                    when ADDR_IER =>
                        rdata_data <= (1 => int_ier(1), 0 => int_ier(0), others => '0');
                    when ADDR_ISR =>
                        rdata_data <= (1 => int_isr(1), 0 => int_isr(0), others => '0');
                    when ADDR_DATA_IN_SIZE_X_DATA_0 =>
                        rdata_data <= RESIZE(int_data_in_size_x(31 downto 0), 32);
                    when ADDR_DATA_IN_SIZE_Y_DATA_0 =>
                        rdata_data <= RESIZE(int_data_in_size_y(31 downto 0), 32);
                    when ADDR_DATA_IN_SIZE_Z_DATA_0 =>
                        rdata_data <= RESIZE(int_data_in_size_z(31 downto 0), 32);
                    when ADDR_CONV_SIZE_X_DATA_0 =>
                        rdata_data <= RESIZE(int_conv_size_x(31 downto 0), 32);
                    when ADDR_CONV_SIZE_Y_DATA_0 =>
                        rdata_data <= RESIZE(int_conv_size_y(31 downto 0), 32);
                    when ADDR_CONV_SIZE_Z_DATA_0 =>
                        rdata_data <= RESIZE(int_conv_size_z(31 downto 0), 32);
                    when ADDR_RELU_SIZE_X_DATA_0 =>
                        rdata_data <= RESIZE(int_relu_size_x(31 downto 0), 32);
                    when ADDR_RELU_SIZE_Y_DATA_0 =>
                        rdata_data <= RESIZE(int_relu_size_y(31 downto 0), 32);
                    when ADDR_RELU_SIZE_Z_DATA_0 =>
                        rdata_data <= RESIZE(int_relu_size_z(31 downto 0), 32);
                    when ADDR_POOL_SIZE_X_DATA_0 =>
                        rdata_data <= RESIZE(int_pool_size_x(31 downto 0), 32);
                    when ADDR_POOL_SIZE_Y_DATA_0 =>
                        rdata_data <= RESIZE(int_pool_size_y(31 downto 0), 32);
                    when ADDR_POOL_SIZE_Z_DATA_0 =>
                        rdata_data <= RESIZE(int_pool_size_z(31 downto 0), 32);
                    when ADDR_FC_SIZE_X_DATA_0 =>
                        rdata_data <= RESIZE(int_fc_size_x(31 downto 0), 32);
                    when ADDR_FC_SIZE_Y_DATA_0 =>
                        rdata_data <= RESIZE(int_fc_size_y(31 downto 0), 32);
                    when ADDR_FC_SIZE_Z_DATA_0 =>
                        rdata_data <= RESIZE(int_fc_size_z(31 downto 0), 32);
                    when ADDR_DATA_OUT_SIZE_X_DATA_0 =>
                        rdata_data <= RESIZE(int_data_out_size_x(31 downto 0), 32);
                    when ADDR_DATA_OUT_SIZE_Y_DATA_0 =>
                        rdata_data <= RESIZE(int_data_out_size_y(31 downto 0), 32);
                    when ADDR_DATA_OUT_SIZE_Z_DATA_0 =>
                        rdata_data <= RESIZE(int_data_out_size_z(31 downto 0), 32);
                    when others =>
                        rdata_data <= (others => '0');
                    end case;
                elsif (int_data_in_data_V_read = '1') then
                    rdata_data <= int_data_in_data_V_q1;
                elsif (int_conv_data_V_read = '1') then
                    rdata_data <= int_conv_data_V_q1;
                elsif (int_relu_data_V_read = '1') then
                    rdata_data <= int_relu_data_V_q1;
                elsif (int_pool_data_V_read = '1') then
                    rdata_data <= int_pool_data_V_q1;
                elsif (int_fc_data_V_read = '1') then
                    rdata_data <= int_fc_data_V_q1;
                elsif (int_data_out_data_V_read = '1') then
                    rdata_data <= int_data_out_data_V_q1;
                end if;
            end if;
        end if;
    end process;

-- ----------------------- Register logic ----------------
    interrupt            <= int_gie and (int_isr(0) or int_isr(1));
    ap_start             <= int_ap_start;
    data_in_size_x       <= STD_LOGIC_VECTOR(int_data_in_size_x);
    data_in_size_y       <= STD_LOGIC_VECTOR(int_data_in_size_y);
    data_in_size_z       <= STD_LOGIC_VECTOR(int_data_in_size_z);
    conv_size_x          <= STD_LOGIC_VECTOR(int_conv_size_x);
    conv_size_y          <= STD_LOGIC_VECTOR(int_conv_size_y);
    conv_size_z          <= STD_LOGIC_VECTOR(int_conv_size_z);
    relu_size_x          <= STD_LOGIC_VECTOR(int_relu_size_x);
    relu_size_y          <= STD_LOGIC_VECTOR(int_relu_size_y);
    relu_size_z          <= STD_LOGIC_VECTOR(int_relu_size_z);
    pool_size_x          <= STD_LOGIC_VECTOR(int_pool_size_x);
    pool_size_y          <= STD_LOGIC_VECTOR(int_pool_size_y);
    pool_size_z          <= STD_LOGIC_VECTOR(int_pool_size_z);
    fc_size_x            <= STD_LOGIC_VECTOR(int_fc_size_x);
    fc_size_y            <= STD_LOGIC_VECTOR(int_fc_size_y);
    fc_size_z            <= STD_LOGIC_VECTOR(int_fc_size_z);
    data_out_size_x      <= STD_LOGIC_VECTOR(int_data_out_size_x);
    data_out_size_y      <= STD_LOGIC_VECTOR(int_data_out_size_y);
    data_out_size_z      <= STD_LOGIC_VECTOR(int_data_out_size_z);

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_ap_start <= '0';
            elsif (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_AP_CTRL and WSTRB(0) = '1' and WDATA(0) = '1') then
                    int_ap_start <= '1';
                elsif (ap_ready = '1') then
                    int_ap_start <= int_auto_restart; -- clear on handshake/auto restart
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_ap_done <= '0';
            elsif (ACLK_EN = '1') then
                if (ap_done = '1') then
                    int_ap_done <= '1';
                elsif (ar_hs = '1' and raddr = ADDR_AP_CTRL) then
                    int_ap_done <= '0'; -- clear on read
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_ap_idle <= '0';
            elsif (ACLK_EN = '1') then
                if (true) then
                    int_ap_idle <= ap_idle;
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_ap_ready <= '0';
            elsif (ACLK_EN = '1') then
                if (true) then
                    int_ap_ready <= ap_ready;
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_auto_restart <= '0';
            elsif (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_AP_CTRL and WSTRB(0) = '1') then
                    int_auto_restart <= WDATA(7);
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_gie <= '0';
            elsif (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_GIE and WSTRB(0) = '1') then
                    int_gie <= WDATA(0);
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_ier <= "00";
            elsif (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_IER and WSTRB(0) = '1') then
                    int_ier <= UNSIGNED(WDATA(1 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_isr(0) <= '0';
            elsif (ACLK_EN = '1') then
                if (int_ier(0) = '1' and ap_done = '1') then
                    int_isr(0) <= '1';
                elsif (w_hs = '1' and waddr = ADDR_ISR and WSTRB(0) = '1') then
                    int_isr(0) <= int_isr(0) xor WDATA(0); -- toggle on write
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_isr(1) <= '0';
            elsif (ACLK_EN = '1') then
                if (int_ier(1) = '1' and ap_ready = '1') then
                    int_isr(1) <= '1';
                elsif (w_hs = '1' and waddr = ADDR_ISR and WSTRB(0) = '1') then
                    int_isr(1) <= int_isr(1) xor WDATA(1); -- toggle on write
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_DATA_IN_SIZE_X_DATA_0) then
                    int_data_in_size_x(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_data_in_size_x(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_DATA_IN_SIZE_Y_DATA_0) then
                    int_data_in_size_y(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_data_in_size_y(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_DATA_IN_SIZE_Z_DATA_0) then
                    int_data_in_size_z(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_data_in_size_z(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_CONV_SIZE_X_DATA_0) then
                    int_conv_size_x(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_conv_size_x(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_CONV_SIZE_Y_DATA_0) then
                    int_conv_size_y(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_conv_size_y(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_CONV_SIZE_Z_DATA_0) then
                    int_conv_size_z(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_conv_size_z(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_RELU_SIZE_X_DATA_0) then
                    int_relu_size_x(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_relu_size_x(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_RELU_SIZE_Y_DATA_0) then
                    int_relu_size_y(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_relu_size_y(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_RELU_SIZE_Z_DATA_0) then
                    int_relu_size_z(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_relu_size_z(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_POOL_SIZE_X_DATA_0) then
                    int_pool_size_x(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_pool_size_x(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_POOL_SIZE_Y_DATA_0) then
                    int_pool_size_y(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_pool_size_y(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_POOL_SIZE_Z_DATA_0) then
                    int_pool_size_z(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_pool_size_z(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_FC_SIZE_X_DATA_0) then
                    int_fc_size_x(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_fc_size_x(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_FC_SIZE_Y_DATA_0) then
                    int_fc_size_y(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_fc_size_y(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_FC_SIZE_Z_DATA_0) then
                    int_fc_size_z(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_fc_size_z(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_DATA_OUT_SIZE_X_DATA_0) then
                    int_data_out_size_x(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_data_out_size_x(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_DATA_OUT_SIZE_Y_DATA_0) then
                    int_data_out_size_y(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_data_out_size_y(31 downto 0));
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (w_hs = '1' and waddr = ADDR_DATA_OUT_SIZE_Z_DATA_0) then
                    int_data_out_size_z(31 downto 0) <= (UNSIGNED(WDATA(31 downto 0)) and wmask(31 downto 0)) or ((not wmask(31 downto 0)) and int_data_out_size_z(31 downto 0));
                end if;
            end if;
        end if;
    end process;


-- ----------------------- Memory logic ------------------
    -- data_in_data_V
    int_data_in_data_V_address0 <= SHIFT_RIGHT(UNSIGNED(data_in_data_V_address0), 1)(1 downto 0);
    int_data_in_data_V_ce0 <= data_in_data_V_ce0;
    int_data_in_data_V_we0 <= '0';
    int_data_in_data_V_be0 <= (others => '0');
    int_data_in_data_V_d0 <= (others => '0');
    data_in_data_V_q0    <= STD_LOGIC_VECTOR(SHIFT_RIGHT(int_data_in_data_V_q0, TO_INTEGER(int_data_in_data_V_shift) * 16)(15 downto 0));
    int_data_in_data_V_address1 <= raddr(3 downto 2) when ar_hs = '1' else waddr(3 downto 2);
    int_data_in_data_V_ce1 <= '1' when ar_hs = '1' or (int_data_in_data_V_write = '1' and WVALID  = '1') else '0';
    int_data_in_data_V_we1 <= '1' when int_data_in_data_V_write = '1' and WVALID = '1' else '0';
    int_data_in_data_V_be1 <= UNSIGNED(WSTRB);
    int_data_in_data_V_d1 <= UNSIGNED(WDATA);
    -- conv_data_V
    int_conv_data_V_address0 <= SHIFT_RIGHT(UNSIGNED(conv_data_V_address0), 1)(1 downto 0);
    int_conv_data_V_ce0  <= conv_data_V_ce0;
    int_conv_data_V_we0  <= conv_data_V_we0;
    int_conv_data_V_be0  <= SHIFT_LEFT(TO_UNSIGNED(3, 4), TO_INTEGER(UNSIGNED(conv_data_V_address0(0 downto 0)))*2);
    int_conv_data_V_d0   <= UNSIGNED(conv_data_V_d0) & UNSIGNED(conv_data_V_d0);
    int_conv_data_V_address1 <= raddr(3 downto 2) when ar_hs = '1' else waddr(3 downto 2);
    int_conv_data_V_ce1  <= '1' when ar_hs = '1' or (int_conv_data_V_write = '1' and WVALID  = '1') else '0';
    int_conv_data_V_we1  <= '1' when int_conv_data_V_write = '1' and WVALID = '1' else '0';
    int_conv_data_V_be1  <= UNSIGNED(WSTRB);
    int_conv_data_V_d1   <= UNSIGNED(WDATA);
    -- relu_data_V
    int_relu_data_V_address0 <= SHIFT_RIGHT(UNSIGNED(relu_data_V_address0), 1)(1 downto 0);
    int_relu_data_V_ce0  <= relu_data_V_ce0;
    int_relu_data_V_we0  <= relu_data_V_we0;
    int_relu_data_V_be0  <= SHIFT_LEFT(TO_UNSIGNED(3, 4), TO_INTEGER(UNSIGNED(relu_data_V_address0(0 downto 0)))*2);
    int_relu_data_V_d0   <= UNSIGNED(relu_data_V_d0) & UNSIGNED(relu_data_V_d0);
    int_relu_data_V_address1 <= raddr(3 downto 2) when ar_hs = '1' else waddr(3 downto 2);
    int_relu_data_V_ce1  <= '1' when ar_hs = '1' or (int_relu_data_V_write = '1' and WVALID  = '1') else '0';
    int_relu_data_V_we1  <= '1' when int_relu_data_V_write = '1' and WVALID = '1' else '0';
    int_relu_data_V_be1  <= UNSIGNED(WSTRB);
    int_relu_data_V_d1   <= UNSIGNED(WDATA);
    -- pool_data_V
    int_pool_data_V_address0 <= SHIFT_RIGHT(UNSIGNED(pool_data_V_address0), 1)(1 downto 0);
    int_pool_data_V_ce0  <= pool_data_V_ce0;
    int_pool_data_V_we0  <= pool_data_V_we0;
    int_pool_data_V_be0  <= SHIFT_LEFT(TO_UNSIGNED(3, 4), TO_INTEGER(UNSIGNED(pool_data_V_address0(0 downto 0)))*2);
    int_pool_data_V_d0   <= UNSIGNED(pool_data_V_d0) & UNSIGNED(pool_data_V_d0);
    int_pool_data_V_address1 <= raddr(3 downto 2) when ar_hs = '1' else waddr(3 downto 2);
    int_pool_data_V_ce1  <= '1' when ar_hs = '1' or (int_pool_data_V_write = '1' and WVALID  = '1') else '0';
    int_pool_data_V_we1  <= '1' when int_pool_data_V_write = '1' and WVALID = '1' else '0';
    int_pool_data_V_be1  <= UNSIGNED(WSTRB);
    int_pool_data_V_d1   <= UNSIGNED(WDATA);
    -- fc_data_V
    int_fc_data_V_address0 <= SHIFT_RIGHT(UNSIGNED(fc_data_V_address0), 1)(1 downto 0);
    int_fc_data_V_ce0    <= fc_data_V_ce0;
    int_fc_data_V_we0    <= fc_data_V_we0;
    int_fc_data_V_be0    <= SHIFT_LEFT(TO_UNSIGNED(3, 4), TO_INTEGER(UNSIGNED(fc_data_V_address0(0 downto 0)))*2);
    int_fc_data_V_d0     <= UNSIGNED(fc_data_V_d0) & UNSIGNED(fc_data_V_d0);
    int_fc_data_V_address1 <= raddr(3 downto 2) when ar_hs = '1' else waddr(3 downto 2);
    int_fc_data_V_ce1    <= '1' when ar_hs = '1' or (int_fc_data_V_write = '1' and WVALID  = '1') else '0';
    int_fc_data_V_we1    <= '1' when int_fc_data_V_write = '1' and WVALID = '1' else '0';
    int_fc_data_V_be1    <= UNSIGNED(WSTRB);
    int_fc_data_V_d1     <= UNSIGNED(WDATA);
    -- data_out_data_V
    int_data_out_data_V_address0 <= SHIFT_RIGHT(UNSIGNED(data_out_data_V_address0), 1)(3 downto 0);
    int_data_out_data_V_ce0 <= data_out_data_V_ce0;
    int_data_out_data_V_we0 <= data_out_data_V_we0;
    int_data_out_data_V_be0 <= SHIFT_LEFT(TO_UNSIGNED(3, 4), TO_INTEGER(UNSIGNED(data_out_data_V_address0(0 downto 0)))*2);
    int_data_out_data_V_d0 <= UNSIGNED(data_out_data_V_d0) & UNSIGNED(data_out_data_V_d0);
    int_data_out_data_V_address1 <= raddr(5 downto 2) when ar_hs = '1' else waddr(5 downto 2);
    int_data_out_data_V_ce1 <= '1' when ar_hs = '1' or (int_data_out_data_V_write = '1' and WVALID  = '1') else '0';
    int_data_out_data_V_we1 <= '1' when int_data_out_data_V_write = '1' and WVALID = '1' else '0';
    int_data_out_data_V_be1 <= UNSIGNED(WSTRB);
    int_data_out_data_V_d1 <= UNSIGNED(WDATA);

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_data_in_data_V_read <= '0';
            elsif (ACLK_EN = '1') then
                if (ar_hs = '1' and raddr >= ADDR_DATA_IN_DATA_V_BASE and raddr <= ADDR_DATA_IN_DATA_V_HIGH) then
                    int_data_in_data_V_read <= '1';
                else
                    int_data_in_data_V_read <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_data_in_data_V_write <= '0';
            elsif (ACLK_EN = '1') then
                if (aw_hs = '1' and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) >= ADDR_DATA_IN_DATA_V_BASE and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) <= ADDR_DATA_IN_DATA_V_HIGH) then
                    int_data_in_data_V_write <= '1';
                elsif (WVALID = '1') then
                    int_data_in_data_V_write <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (data_in_data_V_ce0 = '1') then
                    int_data_in_data_V_shift(0) <= data_in_data_V_address0(0);
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_conv_data_V_read <= '0';
            elsif (ACLK_EN = '1') then
                if (ar_hs = '1' and raddr >= ADDR_CONV_DATA_V_BASE and raddr <= ADDR_CONV_DATA_V_HIGH) then
                    int_conv_data_V_read <= '1';
                else
                    int_conv_data_V_read <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_conv_data_V_write <= '0';
            elsif (ACLK_EN = '1') then
                if (aw_hs = '1' and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) >= ADDR_CONV_DATA_V_BASE and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) <= ADDR_CONV_DATA_V_HIGH) then
                    int_conv_data_V_write <= '1';
                elsif (WVALID = '1') then
                    int_conv_data_V_write <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (conv_data_V_ce0 = '1') then
                    int_conv_data_V_shift(0) <= conv_data_V_address0(0);
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_relu_data_V_read <= '0';
            elsif (ACLK_EN = '1') then
                if (ar_hs = '1' and raddr >= ADDR_RELU_DATA_V_BASE and raddr <= ADDR_RELU_DATA_V_HIGH) then
                    int_relu_data_V_read <= '1';
                else
                    int_relu_data_V_read <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_relu_data_V_write <= '0';
            elsif (ACLK_EN = '1') then
                if (aw_hs = '1' and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) >= ADDR_RELU_DATA_V_BASE and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) <= ADDR_RELU_DATA_V_HIGH) then
                    int_relu_data_V_write <= '1';
                elsif (WVALID = '1') then
                    int_relu_data_V_write <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (relu_data_V_ce0 = '1') then
                    int_relu_data_V_shift(0) <= relu_data_V_address0(0);
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_pool_data_V_read <= '0';
            elsif (ACLK_EN = '1') then
                if (ar_hs = '1' and raddr >= ADDR_POOL_DATA_V_BASE and raddr <= ADDR_POOL_DATA_V_HIGH) then
                    int_pool_data_V_read <= '1';
                else
                    int_pool_data_V_read <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_pool_data_V_write <= '0';
            elsif (ACLK_EN = '1') then
                if (aw_hs = '1' and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) >= ADDR_POOL_DATA_V_BASE and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) <= ADDR_POOL_DATA_V_HIGH) then
                    int_pool_data_V_write <= '1';
                elsif (WVALID = '1') then
                    int_pool_data_V_write <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (pool_data_V_ce0 = '1') then
                    int_pool_data_V_shift(0) <= pool_data_V_address0(0);
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_fc_data_V_read <= '0';
            elsif (ACLK_EN = '1') then
                if (ar_hs = '1' and raddr >= ADDR_FC_DATA_V_BASE and raddr <= ADDR_FC_DATA_V_HIGH) then
                    int_fc_data_V_read <= '1';
                else
                    int_fc_data_V_read <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_fc_data_V_write <= '0';
            elsif (ACLK_EN = '1') then
                if (aw_hs = '1' and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) >= ADDR_FC_DATA_V_BASE and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) <= ADDR_FC_DATA_V_HIGH) then
                    int_fc_data_V_write <= '1';
                elsif (WVALID = '1') then
                    int_fc_data_V_write <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (fc_data_V_ce0 = '1') then
                    int_fc_data_V_shift(0) <= fc_data_V_address0(0);
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_data_out_data_V_read <= '0';
            elsif (ACLK_EN = '1') then
                if (ar_hs = '1' and raddr >= ADDR_DATA_OUT_DATA_V_BASE and raddr <= ADDR_DATA_OUT_DATA_V_HIGH) then
                    int_data_out_data_V_read <= '1';
                else
                    int_data_out_data_V_read <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ARESET = '1') then
                int_data_out_data_V_write <= '0';
            elsif (ACLK_EN = '1') then
                if (aw_hs = '1' and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) >= ADDR_DATA_OUT_DATA_V_BASE and UNSIGNED(AWADDR(ADDR_BITS-1 downto 0)) <= ADDR_DATA_OUT_DATA_V_HIGH) then
                    int_data_out_data_V_write <= '1';
                elsif (WVALID = '1') then
                    int_data_out_data_V_write <= '0';
                end if;
            end if;
        end if;
    end process;

    process (ACLK)
    begin
        if (ACLK'event and ACLK = '1') then
            if (ACLK_EN = '1') then
                if (data_out_data_V_ce0 = '1') then
                    int_data_out_data_V_shift(0) <= data_out_data_V_address0(0);
                end if;
            end if;
        end if;
    end process;


end architecture behave;

library IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;

entity Lenet_axilite_s_axi_ram is
    generic (
        BYTES   : INTEGER :=4;
        DEPTH   : INTEGER :=256;
        AWIDTH  : INTEGER :=8);
    port (
        clk0    : in  STD_LOGIC;
        address0: in  UNSIGNED(AWIDTH-1 downto 0);
        ce0     : in  STD_LOGIC;
        we0     : in  STD_LOGIC;
        be0     : in  UNSIGNED(BYTES-1 downto 0);
        d0      : in  UNSIGNED(BYTES*8-1 downto 0);
        q0      : out UNSIGNED(BYTES*8-1 downto 0);
        clk1    : in  STD_LOGIC;
        address1: in  UNSIGNED(AWIDTH-1 downto 0);
        ce1     : in  STD_LOGIC;
        we1     : in  STD_LOGIC;
        be1     : in  UNSIGNED(BYTES-1 downto 0);
        d1      : in  UNSIGNED(BYTES*8-1 downto 0);
        q1      : out UNSIGNED(BYTES*8-1 downto 0));

end entity Lenet_axilite_s_axi_ram;

architecture behave of Lenet_axilite_s_axi_ram is
    signal address0_tmp : UNSIGNED(AWIDTH-1 downto 0);
    signal address1_tmp : UNSIGNED(AWIDTH-1 downto 0);
    type RAM_T is array (0 to DEPTH - 1) of UNSIGNED(BYTES*8 - 1 downto 0);
    shared variable mem : RAM_T := (others => (others => '0'));
begin

    process (address0)
    begin
    address0_tmp <= address0;
    --synthesis translate_off
          if (address0 > DEPTH-1) then
              address0_tmp <= (others => '0');
          else
              address0_tmp <= address0;
          end if;
    --synthesis translate_on
    end process;

    process (address1)
    begin
    address1_tmp <= address1;
    --synthesis translate_off
          if (address1 > DEPTH-1) then
              address1_tmp <= (others => '0');
          else
              address1_tmp <= address1;
          end if;
    --synthesis translate_on
    end process;

    --read port 0
    process (clk0) begin
        if (clk0'event and clk0 = '1') then
            if (ce0 = '1') then
                q0 <= mem(to_integer(address0_tmp));
            end if;
        end if;
    end process;

    --read port 1
    process (clk1) begin
        if (clk1'event and clk1 = '1') then
            if (ce1 = '1') then
                q1 <= mem(to_integer(address1_tmp));
            end if;
        end if;
    end process;

    gen_write : for i in 0 to BYTES - 1 generate
    begin
        --write port 0
        process (clk0)
        begin
            if (clk0'event and clk0 = '1') then
                if (ce0 = '1' and we0 = '1' and be0(i) = '1') then
                    mem(to_integer(address0_tmp))(8*i+7 downto 8*i) := d0(8*i+7 downto 8*i);
                end if;
            end if;
        end process;

        --write port 1
        process (clk1)
        begin
            if (clk1'event and clk1 = '1') then
                if (ce1 = '1' and we1 = '1' and be1(i) = '1') then
                    mem(to_integer(address1_tmp))(8*i+7 downto 8*i) := d1(8*i+7 downto 8*i);
                end if;
            end if;
        end process;

    end generate;

end architecture behave;


